# Generated by Django 4.1.3 on 2022-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('A', 'Admin'), ('C', 'Customer'), ('P', 'Provider'), ('E', 'Employee')], max_length=1, null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive')], max_length=1, null=True)),
                ('notes', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('score', models.FloatField(default=5)),
            ],
        ),
    ]
