# Generated by Django 4.1 on 2022-08-15 07:04

from datetime import datetime
from django.db import migrations, models
from django.utils.dateparse import parse_datetime
from django.utils import timezone


def string_to_date(app, schema_editor):
    Person = app.get_model('person', 'Person')
    for person in Person.objects.all():
        # Change sttring to date
        lastDate = person.birth_date
        newData = datetime.strptime(lastDate, '%d/%m/%Y')
        person.birth_date = newData

        # Change role single letter
        person.role = 'C'
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_name'),
    ]

    operations = [
        migrations.RunPython(string_to_date),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[(
                'A', 'Admin'), ('C', 'Customer'), ('P', 'Provider'), ('E', 'Employee')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(
                choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
    ]
